modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU AGPL 3.0"
[[mods]]
modId = "mcmodwiki"
version = "${file.jarVersion}"
displayName = "MCMOD-Search-Reborn"
logoFile = "logo.jpg"
authors = "cnlimiter"
description = '''
'''
